set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR armv7)
set(CMAKE_CXX_COMPILER /root/.gradle/toolchains/frc/2024/roborio/bin/arm-frc2024-linux-gnueabi-g++ CACHE FILEPATH riocxx)
set(CMAKE_C_COMPILER /root/.gradle/toolchains/frc/2024/roborio/bin/arm-frc2024-linux-gnueabi-gcc CACHE FILEPATH rioc)
set(CMAKE_LINKER /root/.gradle/toolchains/frc/2024/roborio/bin/arm-frc2024-linux-gnueabi-ld CACHE FILEPATH riold)
set(CMAKE_AR /root/.gradle/toolchains/frc/2024/roborio/bin/arm-frc2024-linux-gnueabi-ar CACHE FILEPATH rioar)
set(CMAKE_RANLIB /root/.gradle/toolchains/frc/2024/roborio/bin/arm-frc2024-linux-gnueabi-ranlib CACHE FILEPATH rioranlib)
set(CMAKE_STRIP /root/.gradle/toolchains/frc/2024/roborio/bin/arm-frc2024-linux-gnueabi-strip CACHE FILEPATH riostrip)
set(CMAKE_READELF /root/.gradle/toolchains/frc/2024/roborio/bin/arm-frc2024-linux-gnueabi-readelf CACHE FILEPATH rioreadelf)
